import "./globals.css";
import Navbar from "./components/nav/Navbar";
import Footer from "./components/footer/Footer";

export const metadata = {
  title: "Aesop | Formuations for skin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className=" flex-grow ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
